<a href="https://colab.research.google.com/github/ivywanjage/cdav/blob/main/apple_products_sold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pandas

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import pandas as pd
pd.__version__
pd.set_option("display.max_columns",None)

In [ ]:
counties=pd.Series([4397073,1208333,2162202,1157073])
print(counties)

In [6]:
df=pd.read_csv("/content/apple_products_pricing_2020_2026.csv")
df.head()

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35

In [16]:
df.tail()

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [17]:
df.head(10)

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
5,2020-09-26,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.29,43149.46,-1.7,NaN,In Stock,4.7,45
6,2020-09-27,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,433.06,42587.59,-0.9,NaN,In Stock,4.8,60
7,2020-09-29,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,312.11,26276.64,27.2,NaN,In Stock,4.4,146
8,2020-10-01,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,323.84,31855.01,24.5,Big Billion Days,In Stock,4.7,95
9,2020-10-01,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,390.51,38757.36,9.0,Great Indian Festival,In Stock,4.9,133

In [18]:
df.tail(20)

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
79980,2026-07-31,Amazon,iPhone,iPhone 14 128GB,New,799,78302,503.88,49842.89,36.9,NaN,In Stock,4.8,6543
79981,2026-07-31,Flipkart,iPhone,iPhone 15 128GB,Renewed/Refurbished,799,78302,451.76,39016.28,43.5,NaN,In Stock,4.5,3803
79982,2026-07-31,Flipkart,iPhone,iPhone 15 128GB,New,799,78302,605.37,58534.13,24.2,NaN,In Stock,4.2,2112
79983,2026-07-31,Amazon,iPhone,iPhone 15 128GB,Renewed/Refurbished,799,78302,449.58,38863.40,43.7,NaN,In Stock,4.2,4641
79984,2026-07-31,Flipkart,iPhone,iPhone 15 Pro Max 256GB,New,1199,117502,1018.87,100946.12,15.0,NaN,Low Stock,4.5,4403
79985,2026-07-31,Flipkart,iPhone,iPhone 16 128GB,New,799,78302,695.21,66804.50,13.0,NaN,In Stock,4.7,2994
79986,2026-07-31,Flipkart,iPhone,iPhone 16 128GB,New,799,78302,693.49,69317.61,13.2,NaN,Low Stock,4.5,1162
79987,2026-07-31,Amazon,iPhone,iPhone 16 128GB,New,799,78302,704.55,69188.38,11.8,NaN,In Stock,4.6,2186
79988,2026-07-31,Amazon,iPhone,iPhone 16 128GB,Renewed/Refurbished,799,78302,525.79,44818.21,34.2,NaN,Low Stock,3.9,2016
79989,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,843.77,83516.88,0.6,NaN,Out of Stock,4.7,1060
79990,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,844.47,84171.70,0.5,NaN,In Stock,4.7,893
79991,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,659.77,56416.63,22.3,NaN,In Stock,4.0,853
79992,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,845.93,82352.51,0.4,NaN,In Stock,4.3,1211
79993,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,853.13,82031.15,-0.5,NaN,Low Stock,4.7,1428
79994,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,837.57,82448.67,1.3,NaN,In Stock,4.3,1407
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [19]:
df.shape

(80000, 14)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               80000 non-null  object
 1   Platform           80000 non-null  object
 2   Product_Category   80000 non-null  object
 3   Model_Name         80000 non-null  object
 4   Condition          80000 non-null  object
 5   Launch_Price_USD   80000 non-null  int64
 6   Launch_Price_INR   80000 non-null  int64
 7   Current_Price_USD  80000 non-null  float64
 8   Current_Price_INR  80000 non-null  float64
 9   Discount_Pct       80000 non-null  float64
 10  Sale_Event         6649 non-null   object
 11  Stock_Status       80000 non-null  object
 12  Rating             80000 non-null  float64
 13  Reviews_Count      80000 non-null  int64
dtypes: float64(4), int64(3), object(7)
memory usage: 8.5+ MB

In [21]:
df.describe()

,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Rating,Reviews_Count
count,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000
mean,963.959125,94467.994250,782.769855,74628.342439,21.418826,4.450099,2405.995925
std,470.086413,46068.468464,461.673970,45117.872172,16.697310,0.269782,1973.630852
min,329.000000,32242.000000,109.930000,9157.680000,-2.000000,3.800000,10.000000
25%,599.000000,58702.000000,432.930000,41686.835000,6.700000,4.300000,896.000000
50%,799.000000,78302.000000,699.740000,67324.020000,21.300000,4.400000,1893.500000
75%,1199.000000,117502.000000,989.112500,96568.117500,36.800000,4.700000,3383.000000
max,1999.000000,195902.000000,2038.970000,203668.710000,73.100000,4.900000,11526.000000

In [ ]:
df.columns
#column names

Index(['Date', 'Platform', 'Product_Category', 'Model_Name', 'Condition',
       'Launch_Price_USD', 'Launch_Price_INR', 'Current_Price_USD',
       'Current_Price_INR', 'Discount_Pct', 'Sale_Event', 'Stock_Status',
       'Rating', 'Reviews_Count'],
      dtype='object')

In [ ]:
df.dtypes
#the type of each column

Date                  object
Platform              object
Product_Category      object
Model_Name            object
Condition             object
Launch_Price_USD       int64
Launch_Price_INR       int64
Current_Price_USD    float64
Current_Price_INR    float64
Discount_Pct         float64
Sale_Event            object
Stock_Status          object
Rating               float64
Reviews_Count          int64
dtype: object

In [ ]:
df.index
#the row labels

RangeIndex(start=0, stop=80000, step=1)

In [ ]:
df.size
#the total number of cells

1120000

In [ ]:
df["Product_Category"].unique()
#what values appear in that specific column

array(['Watch', 'iPad', 'iPhone', 'Mac'], dtype=object)

In [ ]:
df[["Model_Name","Product_Category"]]

                        Model_Name Product_Category
0      Apple Watch Series 6 (44mm)            Watch
1      Apple Watch Series 6 (44mm)            Watch
2      Apple Watch Series 6 (44mm)            Watch
3      Apple Watch Series 6 (44mm)            Watch
4      Apple Watch Series 6 (44mm)            Watch
...                            ...              ...
79995              iPhone 17 128GB           iPhone
79996              iPhone 17 128GB           iPhone
79997              iPhone 17 128GB           iPhone
79998              iPhone 17 128GB           iPhone
79999              iPhone 17 128GB           iPhone

[80000 rows x 2 columns]

In [ ]:
df.loc[2,"Platform"]
#row named 2,column named platform

'Amazon'

In [22]:
df.iloc[2,2]
#second row,second column

'Watch'

In [23]:
df["Product_Category"]=="Watch"

0         True
1         True
2         True
3         True
4         True
         ...
79995    False
79996    False
79997    False
79998    False
79999    False
Name: Product_Category, Length: 80000, dtype: bool

In [24]:
df["Reviews_Count"]>1000

0        False
1        False
2        False
3        False
4        False
         ...
79995     True
79996    False
79997     True
79998    False
79999     True
Name: Reviews_Count, Length: 80000, dtype: bool

In [25]:
df["Product_Category"]!="Watch"

0        False
1        False
2        False
3        False
4        False
         ...
79995     True
79996     True
79997     True
79998     True
79999     True
Name: Product_Category, Length: 80000, dtype: bool

In [28]:
s=pd.Series([10,25,30,45])
s>20

0    False
1     True
2     True
3     True
dtype: bool

In [30]:
df[df["Reviews_Count"]>1000]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
1042,2021-03-28,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,421.47,41509.67,1.8,NaN,In Stock,4.4,1009
1054,2021-03-30,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,429.39,42201.01,-0.1,NaN,In Stock,4.3,1029
1065,2021-04-01,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.69,42457.51,-1.8,NaN,Out of Stock,4.5,1123
1074,2021-04-03,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,426.96,42459.53,0.5,NaN,In Stock,4.8,1091
1075,2021-04-03,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,437.07,42698.55,-1.9,NaN,In Stock,4.5,1083
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79993,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,853.13,82031.15,-0.5,NaN,Low Stock,4.7,1428
79994,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,837.57,82448.67,1.3,NaN,In Stock,4.3,1407
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [35]:
is_amazon=df["Platform"]=="Amazon"
is_large=df["Reviews_Count"]>1000
df[is_amazon&is_large]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
1042,2021-03-28,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,421.47,41509.67,1.8,NaN,In Stock,4.4,1009
1054,2021-03-30,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,429.39,42201.01,-0.1,NaN,In Stock,4.3,1029
1074,2021-04-03,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,426.96,42459.53,0.5,NaN,In Stock,4.8,1091
1130,2021-04-10,Amazon,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,341.98,28658.13,20.3,NaN,In Stock,4.1,1018
1145,2021-04-12,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,429.27,41347.28,-0.1,NaN,In Stock,4.5,1015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79988,2026-07-31,Amazon,iPhone,iPhone 16 128GB,Renewed/Refurbished,799,78302,525.79,44818.21,34.2,NaN,Low Stock,3.9,2016
79989,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,843.77,83516.88,0.6,NaN,Out of Stock,4.7,1060
79993,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,853.13,82031.15,-0.5,NaN,Low Stock,4.7,1428
79994,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,837.57,82448.67,1.3,NaN,In Stock,4.3,1407
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020

In [40]:
len(is_amazon)
is_amazon.shape

(80000,)

In [41]:
df[(df["Platform"]=="Amazon") &(df["Reviews_Count"]>1000)]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
1042,2021-03-28,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,421.47,41509.67,1.8,NaN,In Stock,4.4,1009
1054,2021-03-30,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,429.39,42201.01,-0.1,NaN,In Stock,4.3,1029
1074,2021-04-03,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,426.96,42459.53,0.5,NaN,In Stock,4.8,1091
1130,2021-04-10,Amazon,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,341.98,28658.13,20.3,NaN,In Stock,4.1,1018
1145,2021-04-12,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,429.27,41347.28,-0.1,NaN,In Stock,4.5,1015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79988,2026-07-31,Amazon,iPhone,iPhone 16 128GB,Renewed/Refurbished,799,78302,525.79,44818.21,34.2,NaN,Low Stock,3.9,2016
79989,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,843.77,83516.88,0.6,NaN,Out of Stock,4.7,1060
79993,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,853.13,82031.15,-0.5,NaN,Low Stock,4.7,1428
79994,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,837.57,82448.67,1.3,NaN,In Stock,4.3,1407
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020

In [43]:
#NOT amazon-the squiggle means 'not'
df[-(df["Platform"]=="Amazon")]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [44]:
#one of several,without a long chain of ORs
df[df["Product_Category"].isin(["iPhone","Watch","iPad"])]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [45]:
#between-inclusive at both ends
df[df["Reviews_Count"].between(500,1000)]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
348,2020-12-16,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,341.13,29263.92,20.5,NaN,In Stock,4.0,539
349,2020-12-16,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,423.67,41631.01,1.2,NaN,In Stock,4.9,527
362,2020-12-18,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.57,41836.91,0.8,NaN,In Stock,4.3,505
370,2020-12-19,Amazon,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,342.44,29020.31,20.2,NaN,In Stock,3.8,531
445,2020-12-29,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,340.27,28896.60,20.7,NaN,In Stock,4.4,519
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79929,2026-07-30,Amazon,iPhone,iPhone 17 128GB,New,849,83202,834.66,82961.80,1.7,NaN,In Stock,4.8,924
79990,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,844.47,84171.70,0.5,NaN,In Stock,4.7,893
79991,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,659.77,56416.63,22.3,NaN,In Stock,4.0,853
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710

In [52]:
#query-the same filter,written as a sentence
df.query("Platform=='Amazon' and Reviews_Count>1000")

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
1042,2021-03-28,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,421.47,41509.67,1.8,NaN,In Stock,4.4,1009
1054,2021-03-30,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,429.39,42201.01,-0.1,NaN,In Stock,4.3,1029
1074,2021-04-03,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,426.96,42459.53,0.5,NaN,In Stock,4.8,1091
1130,2021-04-10,Amazon,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,341.98,28658.13,20.3,NaN,In Stock,4.1,1018
1145,2021-04-12,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,429.27,41347.28,-0.1,NaN,In Stock,4.5,1015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79988,2026-07-31,Amazon,iPhone,iPhone 16 128GB,Renewed/Refurbished,799,78302,525.79,44818.21,34.2,NaN,Low Stock,3.9,2016
79989,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,843.77,83516.88,0.6,NaN,Out of Stock,4.7,1060
79993,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,853.13,82031.15,-0.5,NaN,Low Stock,4.7,1428
79994,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,837.57,82448.67,1.3,NaN,In Stock,4.3,1407
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020

In [54]:
df["Current_Price_USD"].value_counts()

Current_Price_USD
788.60     13
257.68     11
253.61     10
811.31     10
589.50      9
           ..
787.89      1
896.49      1
1011.59     1
550.48      1
231.97      1
Name: count, Length: 49611, dtype: int64

In [56]:
df['Current_Price_USD'].value_counts(dropna=False)

Current_Price_USD
788.60     13
257.68     11
253.61     10
811.31     10
589.50      9
           ..
787.89      1
896.49      1
1011.59     1
550.48      1
231.97      1
Name: count, Length: 49611, dtype: int64

In [57]:
df['Current_Price_USD'].unique()

array([435.81, 436.49, 422.73, ..., 861.39, 657.3 , 834.95])

In [58]:
df['Current_Price_USD'].nunique()

49611

# data cleaning

In [61]:
#missing data
df.isna()
#true when a value is missing

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,False,False,False,False,False,False,False,False,False,False,True,False,False,False
79996,False,False,False,False,False,False,False,False,False,False,True,False,False,False
79997,False,False,False,False,False,False,False,False,False,False,True,False,False,False
79998,False,False,False,False,False,False,False,False,False,False,True,False,False,False
79999,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [62]:
df.isna().sum()
#count per column,you use this one

Date                     0
Platform                 0
Product_Category         0
Model_Name               0
Condition                0
Launch_Price_USD         0
Launch_Price_INR         0
Current_Price_USD        0
Current_Price_INR        0
Discount_Pct             0
Sale_Event           73351
Stock_Status             0
Rating                   0
Reviews_Count            0
dtype: int64

In [66]:
df.isna().sum().sum()
#total across the whole table

np.int64(73351)

In [67]:
df.isna().mean()*100

Date                  0.00000
Platform              0.00000
Product_Category      0.00000
Model_Name            0.00000
Condition             0.00000
Launch_Price_USD      0.00000
Launch_Price_INR      0.00000
Current_Price_USD     0.00000
Current_Price_INR     0.00000
Discount_Pct          0.00000
Sale_Event           91.68875
Stock_Status          0.00000
Rating                0.00000
Reviews_Count         0.00000
dtype: float64

In [69]:
df.duplicated().sum()

np.int64(0)

In [7]:
df[df.duplicated()]

Empty DataFrame
Columns: [Date, Platform, Product_Category, Model_Name, Condition, Launch_Price_USD, Launch_Price_INR, Current_Price_USD, Current_Price_INR, Discount_Pct, Sale_Event, Stock_Status, Rating, Reviews_Count]
Index: []

In [10]:
df["Reviews_Count"]=df["Reviews_Count"].astype(float)
df

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40.0
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84.0
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110.0
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111.0
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346.0
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802.0
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020.0
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710.0
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022.0

In [11]:
df.memory_usage(deep=True)

Index                    132
Date                 4720000
Platform             4480086
Product_Category     4297023
Model_Name           5722511
Condition            4480240
Launch_Price_USD      640000
Launch_Price_INR      640000
Current_Price_USD     640000
Current_Price_INR     640000
Discount_Pct          640000
Sale_Event           2769466
Stock_Status         4625391
Rating                640000
Reviews_Count         640000
dtype: int64

In [13]:
df.dtypes
#did the type change?

Date                  object
Platform              object
Product_Category      object
Model_Name            object
Condition             object
Launch_Price_USD       int64
Launch_Price_INR       int64
Current_Price_USD    float64
Current_Price_INR    float64
Discount_Pct         float64
Sale_Event            object
Stock_Status          object
Rating               float64
Reviews_Count        float64
dtype: object

In [14]:
df.describe

<bound method NDFrame.describe of              Date  Platform Product_Category                   Model_Name  \
0      2020-09-19  Flipkart            Watch  Apple Watch Series 6 (44mm)
1      2020-09-20  Flipkart            Watch  Apple Watch Series 6 (44mm)
2      2020-09-23    Amazon            Watch  Apple Watch Series 6 (44mm)
3      2020-09-23    Amazon            Watch  Apple Watch Series 6 (44mm)
4      2020-09-24    Amazon            Watch  Apple Watch Series 6 (44mm)
...           ...       ...              ...                          ...
79995  2026-07-31  Flipkart           iPhone              iPhone 17 128GB
79996  2026-07-31  Flipkart           iPhone              iPhone 17 128GB
79997  2026-07-31    Amazon           iPhone              iPhone 17 128GB
79998  2026-07-31  Flipkart           iPhone              iPhone 17 128GB
79999  2026-07-31  Flipkart           iPhone              iPhone 17 128GB

                 Condition  Launch_Price_USD  Launch_Price_INR  \
0                      New               429             42042
1                      New               429             42042
2                      New               429             42042
3                      New               429             42042
4                      New               429             42042
...                    ...               ...               ...
79995                  New               849             83202
79996                  New               849             83202
79997  Renewed/Refurbished               849             83202
79998  Renewed/Refurbished               849             83202
79999                  New               849             83202

       Current_Price_USD  Current_Price_INR  Discount_Pct Sale_Event  \
0                 435.81           43322.41          -1.6        NaN
1                 436.49           42320.43          -1.7        NaN
2                 422.73           40879.36           1.5        NaN
3                 425.00           42008.70           0.9        NaN
4                 436.22           41984.28          -1.7        NaN
...                  ...                ...           ...        ...
79995             861.39           82894.76          -1.5        NaN
79996             832.50           81159.39           1.9        NaN
79997             657.30           56336.73          22.6        NaN
79998             709.49           61361.07          16.4        NaN
79999             834.95           83035.30           1.7        NaN

       Stock_Status  Rating  Reviews_Count
0          In Stock     4.7           40.0
1      Out of Stock     4.6           84.0
2          In Stock     4.4          110.0
3          In Stock     4.8          111.0
4          In Stock     4.7           35.0
...             ...     ...            ...
79995      In Stock     4.7         1346.0
79996      In Stock     4.7          802.0
79997      In Stock     4.2         1020.0
79998      In Stock     3.9          710.0
79999     Low Stock     4.8         1022.0

[80000 rows x 14 columns]>

In [17]:
df.isna().sum()
#repeated(first one is at the top)

Date                     0
Platform                 0
Product_Category         0
Model_Name               0
Condition                0
Launch_Price_USD         0
Launch_Price_INR         0
Current_Price_USD        0
Current_Price_INR        0
Discount_Pct             0
Sale_Event           73351
Stock_Status             0
Rating                   0
Reviews_Count            0
dtype: int64

# saving your clean data

In [19]:
#df.to_csv("transctions_clean.csv",index=False)
#check it worked by loading it back
#check=pd.read_csv("transactions_clean.csv")
#check.shape